version: '3.7'

services:
    pgweb:
        restart: always
        image: sosedoff/pgweb
        env_file: env/db.env
        ports: 
            - "${FORWARD_DBMA_PORT:-7070}:8081"
        environment:
            - DATABASE_URL=postgres://odoo:${POSTGRES_PASSWORD}@db:5432/odoo?sslmode=disable
        links:
            - db
    