version: '3.7'

adminer:
    image: adminer:latest
    ports:
        - "${_CM_ENV_FORWARD_DBMA_PORT:-7070}:80"
    env_file:
        - env/db.env
    links:
        - db
    environment:
        ADMINER_DEFAULT_SERVER: db
        ADMINER_DESIGN: galkaev
        TZ: Asia/Ho_Chi_Minh