version: '3.7'

services:
    app:
        build:
            context: images/odoo/16.0
            args:
                _UID: "${_UID:-1000}"
                _GID: "${_GID:-1000}"
                _ARCH: "${_ARCH:-amd64}"
        env_file: env/db.env
        ports:
            - "${FORWARD_HTTP_PORT:-80}:8069"
            - "${FORWARD_DEBUG_PORT:-9003}:5678"
        volumes:
            - ./data/odoo:/var/lib/odoo
            - ./addons:/mnt/extra-addons
        environment:
            - TZ=Asia/Ho_Chi_Minh
            - IS_DEBUG=${IS_DEBUG:-false}
        links:
            - db

    db:
        image: postgres:15
        env_file: env/db.env
        user: "${_UID:-1000}:${_GID:-1000}" 
        ports:
            - "${FORWARD_DB_PORT:-3306}:5432"
        environment:
            TZ: Asia/Ho_Chi_Minh
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data:delegated
            - /etc/passwd:/etc/passwd:ro
